# frozen_string_literal: true

require 'yaml'

opts = YAML.load_file 'config.yml'

Vagrant.configure('2') do |config|
  config.ssh.username = opts['ansible_user']
  config.ssh.private_key_path = opts['ansible_key'] || "#{ENV['HOME']}/.cache/packer/ssh_private_key_packerarchsetup_rsa.pem"

  config.vm.box = opts['box']

  config.vm.define opts['name'] do |node|
    node.vm.hostname = opts['name']
    #node.vm.network 'private_network', iop: opts['ip']

    node.vm.provider :libvirt do |libvirt|
      libvirt.cpus = opts['cpu']
      libvirt.memory = opts['memory']
      libvirt.loader = '/usr/share/ovmf/x64/OVMF.fd'
    end
  end
end
